---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  namespace: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid 
        image: docker.pkg.github.com/hanyhesham/s-k8-proxy-rebuild/squid-reverse:latest
        imagePullPolicy: "Always"
        env:
          - name: ALLOWED_DOMAINS
            value: gov.uk.glasswall-icap.com,www.gov.uk.glasswall-icap.com,assets.publishing.service.gov.uk.glasswall-icap.com
          - name: ICAP_URL
            value: icap://icap:1344/gw_rebuild
          - name: ROOT_DOMAIN
            value: glasswall-icap.com
---
apiVersion: v1
kind: Service
metadata:
  name: squid
  namespace: reverse-proxy
spec:
  type: NodePort
  selector:
    app: squid
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
